name: Update Site Info
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate site info
        run: |
          # Get latest commit date
          LATEST_DATE=$(git log -1 --format=%cd --date=short)
          
          # Count lines of code
          LOC=$(find . -name "*.html" -o -name "*.js" -path "./js/*" -o -name "*.css" -path "./styles/*" | xargs wc -l | tail -1 | awk '{print $1}')
          
          # Create data.js
          cat > js/data.js << EOF
          window.siteInfo = {
            latest: "$LATEST_DATE",
            loc: $LOC
          };
          EOF
          
      - name: Commit data.js
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add js/data.js
          git diff --staged --quiet || git commit -m "Update site info"
          git push
